In [1]:
import numpy as np

In [2]:
# Define a matrix A
A = np.array([[4, 0], 
              [3, -5]])

# Perform SVD
U, S, Vt = np.linalg.svd(A)

# Print results
print("U Matrix:\n", U)
print("Singular Values:\n", S)
print("V Transposed Matrix:\n", Vt)

U Matrix:
 [[-0.4472136  -0.89442719]
 [-0.89442719  0.4472136 ]]
Singular Values:
 [6.32455532 3.16227766]
V Transposed Matrix:
 [[-0.70710678  0.70710678]
 [-0.70710678 -0.70710678]]


In [5]:
np.diag(S)

array([[6.32455532, 0.        ],
       [0.        , 3.16227766]])